# fly.prod.toml - Production environment
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'tourrankings'
primary_region = 'syd'

[[vm]]
memory = '1024mb'
swap_size_mb = 512
cpu_kind = 'shared'
cpus = 1

[deploy]
wait_timeout = "10m"

[mounts]
source = "data_volume"
destination = "/tourRanking/data"

[build]
dockerfile = "Dockerfile"
ignorefile = ".dockerignore"

[http_service]
processes = ["app"]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = "production"
LOG_LEVEL = "debug"
DATA_AUTO_REFRESH = true
DATA_AUTO_REFRESH_INTERVAL = 1800000

[processes]
# app = "sh -c 'supercronic -passthrough-logs /tourRanking/crontab & exec bun start'"
app = "sh -c 'bun start'"

# Production health checks
# [checks]
# [checks.health]
# grace_period = "30s"
# interval = "30s"
# method = "GET"
# path = "/health"
# port = 8080
# timeout = "10s"
# headers = []
