# fly.prod.toml - Production environment
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'tourrankings'
primary_region = 'syd'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1
max_machines_running = 2

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
NODE_ENV = "production"
LOG_LEVEL = "info"
DATA_AUTO_REFRESH = true
DATA_AUTO_REFRESH_INTERVAL = 1800000

# Production health checks
[checks]
[checks.health]
grace_period = "30s"
interval = "30s"
method = "GET"
path = "/health"
port = 8080
timeout = "10s"
headers = []

[mounts]
source = "data_volume"
destination = "/tourRanking/data"
