# fly.dev.toml - Development environment
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'tourrankings-dev'
primary_region = 'syd'

[[vm]]
memory = '1024mb'
swap_size_mb = 512
cpu_kind = 'shared'
cpus = 1

[deploy]
wait_timeout = "10m"

[mounts]
source = "dev_data_volume"
destination = "/tourRanking/data"

[build]
dockerfile = "Dockerfile.dev"
ignorefile = ".dockerignore"

[http_service]
processes = ["app"]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend' # Faster wake-up than 'stop'
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = "development"
LOG_LEVEL = "debug"
DATA_AUTO_REFRESH = true
DATA_AUTO_REFRESH_INTERVAL = 1800000

[processes]
app = "sh -c 'supercronic -passthrough-logs /tourRanking/crontab & exec bun start'"
