# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'tourrankings'
primary_region = 'syd'

[build]
dockerfile = "Dockerfile"

[processes]
web = "bun start"
cron = "supercronic /app/crontab"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['web']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "data_volume"
destination = "/app/data"
