# fly.dev.toml - Development environment
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'tourrankings-dev'
primary_region = 'syd'

[build]
dockerfile = "Dockerfile.dev"
ignorefile = ".dockerignore"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
NODE_ENV = "development"
LOG_LEVEL = "debug"

[mounts]
source = "dev_data_volume"
destination = "/tourRanking/data"

[processes]
app = "sh -c 'supercronic -passthrough-logs /tourRanking/crontab & bun start'"

[http_service]
processes = ["app"]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend' # Faster wake-up than 'stop'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1
