# .github/workflows/issue-management-cooldown.yml
name: Cooldown Management

on:
  issues:
    types: [labeled]

jobs:
  move-to-cooldown:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Add to cooldown
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Cooldown Board
          column: Bug Fixes
